import { AlertTriangle, Lock } from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { AppSettings } from "@/lib/settingsTypes";

interface HttpsSettingsProps {
  settings: AppSettings;
  originalSettings: AppSettings | null;
  updateSetting: <K extends keyof AppSettings>(
    key: K,
    value: AppSettings[K],
  ) => void;
  applyRecommendedHttpsDefaults: () => void;
  hasPartialHttpsCertPath: boolean;
  usingAutoGeneratedHttpsCert: boolean;
  httpPreviewUrl: string;
  httpsPreviewUrl: string;
}

export function HttpsSettings({
  settings,
  originalSettings,
  updateSetting,
  applyRecommendedHttpsDefaults,
  hasPartialHttpsCertPath,
  usingAutoGeneratedHttpsCert,
  httpPreviewUrl,
  httpsPreviewUrl,
}: HttpsSettingsProps) {
  return (
    <Card id="settings-https">
      <CardHeader className="pb-4">
        <CardTitle className="flex items-center gap-2">
          <Lock className="w-4 h-4 text-primary" />
          HTTPS
        </CardTitle>
        <CardDescription>
          Encrypt panel traffic with a TLS certificate.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <Alert className="border-border/60 bg-muted/40">
          <Lock className="h-4 w-4 text-primary" />
          <AlertTitle>Recommended Setup (Most Servers)</AlertTitle>
          <AlertDescription className="space-y-2 text-sm text-muted-foreground">
            <p>
              Enable HTTPS, leave certificate paths empty, save, then
              restart.
            </p>
            <p>
              The panel creates a local self-signed certificate
              automatically.
            </p>
            <div className="flex flex-wrap gap-2 pt-1">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={applyRecommendedHttpsDefaults}
              >
                Use Recommended Defaults
              </Button>
            </div>
          </AlertDescription>
        </Alert>

        <div className="flex items-center gap-3 p-4 rounded-xl bg-muted/50">
          <Switch
            checked={settings.httpsEnabled}
            onCheckedChange={(value) => updateSetting("httpsEnabled", value)}
            aria-label="Enable HTTPS"
          />
          <div>
            <Label className="text-base">Enable HTTPS</Label>
            <p className="text-sm text-muted-foreground">
              Serve the panel over HTTPS.
            </p>
          </div>
        </div>

        <div className="rounded-xl border border-border/60 bg-background/50 p-3 text-xs text-muted-foreground space-y-1">
          <p>
            <strong className="text-foreground">HTTP URL:</strong>{" "}
            <code className="break-all">{httpPreviewUrl}</code>
          </p>
          <p>
            <strong className="text-foreground">HTTPS URL:</strong>{" "}
            <code className="break-all">{httpsPreviewUrl}</code>
          </p>
        </div>

        {settings.httpsEnabled && (
          <div className="ml-2 space-y-4 border-l-2 border-primary/20 pl-2">
            <div className="max-w-xs">
              <Label htmlFor="https-port">HTTPS Port</Label>
              <Input
                id="https-port"
                type="number"
                value={settings.httpsPort}
                onChange={(e) => updateSetting("httpsPort", e.target.value)}
                onWheel={(e) => e.currentTarget.blur()}
                min="1024"
                max="65535"
                placeholder="3443"
                inputMode="numeric"
              />
              <p className="text-xs text-muted-foreground mt-1">
                HTTPS listener port (recommended 3443).
              </p>
            </div>
            <div className="max-w-md">
              <Label htmlFor="https-cert-path">
                Custom Certificate Path{" "}
                <span className="text-muted-foreground font-normal">
                  (optional)
                </span>
              </Label>
              <Input
                id="https-cert-path"
                value={settings.httpsCertPath}
                onChange={(e) =>
                  updateSetting("httpsCertPath", e.target.value)
                }
                placeholder="Example: C:\\certs\\panel.fullchain.pem"
                maxLength={260}
              />
              <p className="text-xs text-muted-foreground mt-1">
                Set both certificate and key paths, or leave both empty.
              </p>
            </div>
            <div className="max-w-md">
              <Label htmlFor="https-key-path">
                Custom Key Path{" "}
                <span className="text-muted-foreground font-normal">
                  (optional)
                </span>
              </Label>
              <Input
                id="https-key-path"
                value={settings.httpsKeyPath}
                onChange={(e) => updateSetting("httpsKeyPath", e.target.value)}
                placeholder="Example: C:\\certs\\panel.privkey.pem"
                maxLength={260}
              />
              <p className="text-xs text-muted-foreground mt-1">
                Supports PEM key files that Node.js can read.
              </p>
            </div>

            {hasPartialHttpsCertPath && (
              <Alert className="border-warning/40 bg-warning/10">
                <AlertTriangle className="h-4 w-4 text-warning" />
                <AlertTitle className="text-warning">
                  Provide Both Certificate Files
                </AlertTitle>
                <AlertDescription>
                  Set both certificate and key paths, or clear both to use
                  auto-generated certs.
                </AlertDescription>
              </Alert>
            )}

            {usingAutoGeneratedHttpsCert && (
              <Alert className="border-primary/30 bg-primary/10">
                <Lock className="h-4 w-4 text-primary" />
                <AlertTitle className="text-primary">
                  Auto-Generated Certificate Mode
                </AlertTitle>
                <AlertDescription>
                  The panel will create and reuse a local self-signed
                  certificate.
                </AlertDescription>
              </Alert>
            )}

            <Alert className="border-border/60 bg-muted/35">
              <Lock className="h-4 w-4 text-muted-foreground" />
              <AlertTitle>Reverse Proxy Note</AlertTitle>
              <AlertDescription>
                If TLS is terminated by Nginx, Caddy, or Cloudflare Tunnel,
                keep panel HTTPS off and proxy local HTTP.
              </AlertDescription>
            </Alert>

            {originalSettings &&
              settings.httpsEnabled !== originalSettings.httpsEnabled && (
                <Alert className="border-warning/40 bg-warning/10">
                  <AlertTriangle className="h-4 w-4 text-warning" />
                  <AlertTitle className="text-warning">
                    Restart Required
                  </AlertTitle>
                  <AlertDescription>
                    HTTPS changes require restart. Save first, then restart
                    from Panel Settings.
                  </AlertDescription>
                </Alert>
              )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
