import type { Socket } from "socket.io-client";
import { TabsContent } from "@/components/ui/tabs";
import { useAppSettingsCore } from "@/hooks/settings/useAppSettingsCore";
import { useCorsSettings } from "@/hooks/settings/useCorsSettings";
import { usePanelUpdateSettings } from "@/hooks/settings/usePanelUpdateSettings";
import { GeneralSettings } from "./GeneralSettings";
import { AccessSettings } from "./AccessSettings";
import { UpdatesSettings } from "./UpdatesSettings";
import { HttpsSettings } from "./HttpsSettings";
import { ConnectionSettings } from "./ConnectionSettings";
import { BridgeSettings } from "./BridgeSettings";
import { ModsSettings } from "./ModsSettings";
import { BackupsSettings } from "./BackupsSettings";
import { PushoverSettings } from "./PushoverSettings";
import { SecuritySettings } from "./SecuritySettings";
import { AboutSettings } from "./AboutSettings";
import { MapSettings } from "./MapSettings";

interface AuthUser {
  username: string;
  role: string;
}

interface HttpsPreview {
  applyRecommendedHttpsDefaults: () => void;
  hasPartialHttpsCertPath: boolean;
  usingAutoGeneratedHttpsCert: boolean;
  httpPreviewUrl: string;
  httpsPreviewUrl: string;
}

interface SettingsTabPanelsProps {
  socket: Socket | null;
  core: ReturnType<typeof useAppSettingsCore>;
  cors: ReturnType<typeof useCorsSettings>;
  panelUpdate: ReturnType<typeof usePanelUpdateSettings>;
  https: HttpsPreview;
  authEnabled: boolean;
  user: AuthUser | null;
  logout: () => Promise<void>;
}

// One TabsContent per settings section. Kept as a single composition file
// so Settings.tsx only wires up hooks and tab navigation.
export function SettingsTabPanels({
  socket,
  core,
  cors,
  panelUpdate,
  https,
  authEnabled,
  user,
  logout,
}: SettingsTabPanelsProps) {
  return (
    <>
      <TabsContent value="general" className="mt-0">
        <GeneralSettings
          settings={core.settings}
          originalSettings={core.originalSettings}
          updateSetting={core.updateSetting}
          isDirty={core.isDirty}
          restarting={core.restarting}
          restartPanelWithReconnect={core.restartPanelWithReconnect}
        />
      </TabsContent>

      <TabsContent value="access" className="mt-0">
        <AccessSettings
          settings={core.settings}
          updateSetting={core.updateSetting}
          networkInterfaces={cors.networkInterfaces}
          corsOriginValidationError={core.corsOriginValidationError}
          corsDiagnostics={cors.corsDiagnostics}
          corsLoading={cors.corsLoading}
          corsUpdating={cors.corsUpdating}
          saving={core.saving}
          handleCorsLanToggle={cors.handleCorsLanToggle}
          handleReloadCorsRules={cors.handleReloadCorsRules}
          fetchCorsDiagnostics={cors.fetchCorsDiagnostics}
          handleClearCorsBlocked={cors.handleClearCorsBlocked}
        />
      </TabsContent>

      <TabsContent value="updates" className="mt-0">
        <UpdatesSettings
          panelUpdateStatus={panelUpdate.panelUpdateStatus}
          panelUpdateStatusError={panelUpdate.panelUpdateStatusError}
          checkingPanelUpdate={panelUpdate.checkingPanelUpdate}
          downloadingPanelUpdate={panelUpdate.downloadingPanelUpdate}
          dockerUpdateConfirmOpen={panelUpdate.dockerUpdateConfirmOpen}
          setDockerUpdateConfirmOpen={panelUpdate.setDockerUpdateConfirmOpen}
          panelUpdateReady={panelUpdate.panelUpdateReady}
          panelUpdatePreflight={panelUpdate.panelUpdatePreflight}
          panelApplyLog={panelUpdate.panelApplyLog}
          setPanelApplyLog={panelUpdate.setPanelApplyLog}
          panelApplyResultDismissed={panelUpdate.panelApplyResultDismissed}
          setPanelApplyResultDismissed={panelUpdate.setPanelApplyResultDismissed}
          fetchPanelUpdateStatus={panelUpdate.fetchPanelUpdateStatus}
          isDockerPanelUpdate={panelUpdate.isDockerPanelUpdate}
          handleCheckPanelUpdate={panelUpdate.handleCheckPanelUpdate}
          handleDownloadPanelUpdate={panelUpdate.handleDownloadPanelUpdate}
          isDirty={core.isDirty}
          restarting={core.restarting}
          restartPanelWithReconnect={core.restartPanelWithReconnect}
        />
      </TabsContent>

      <TabsContent value="https" className="mt-0">
        <HttpsSettings
          settings={core.settings}
          originalSettings={core.originalSettings}
          updateSetting={core.updateSetting}
          applyRecommendedHttpsDefaults={https.applyRecommendedHttpsDefaults}
          hasPartialHttpsCertPath={https.hasPartialHttpsCertPath}
          usingAutoGeneratedHttpsCert={https.usingAutoGeneratedHttpsCert}
          httpPreviewUrl={https.httpPreviewUrl}
          httpsPreviewUrl={https.httpsPreviewUrl}
        />
      </TabsContent>

      <TabsContent value="connection" className="mt-0 space-y-5">
        <ConnectionSettings settings={core.settings} updateSetting={core.updateSetting} />
      </TabsContent>

      <TabsContent value="bridge" className="mt-0">
        <BridgeSettings
          socket={socket}
          settings={core.settings}
          updateSetting={core.updateSetting}
        />
      </TabsContent>

      <TabsContent value="mods" className="mt-0 space-y-5">
        <ModsSettings
          settings={core.settings}
          updateSetting={core.updateSetting}
          setSettings={core.setSettings}
          setOriginalSettings={core.setOriginalSettings}
        />
      </TabsContent>

      <TabsContent value="backups" className="mt-0 space-y-5">
        <BackupsSettings settings={core.settings} updateSetting={core.updateSetting} />
      </TabsContent>

      <TabsContent value="notifications" className="mt-0 space-y-5">
        <PushoverSettings />
      </TabsContent>

      <TabsContent value="security" className="mt-0">
        <SecuritySettings authEnabled={authEnabled} user={user} logout={logout} />
      </TabsContent>

      <TabsContent value="map" className="mt-0">
        <MapSettings />
      </TabsContent>

      <TabsContent value="about" className="mt-0 space-y-5">
        <AboutSettings panelUpdateStatus={panelUpdate.panelUpdateStatus} />
      </TabsContent>
    </>
  );
}
