// Small helpers shared between the /install and /quick-setup routes.
import path from "path";
import fs from "fs";
import { createLogger } from "../../utils/logger.js";
import { sanitizeIniValue } from "../../utils/sanitize.js";
import { writeFileAtomic } from "../../utils/fileWriteQueue.js";

const log = createLogger("API:Server");

// Pre-creates the server .ini with RCON settings so PZ reads them on first
// boot (PZ reads the INI at startup - if we wait until after, the password
// won't take effect). No-ops if the ini already exists. Returns whether it
// created the file, so callers can decide whether to emit their own
// "precreated" notification (install.js does, quick-setup.js does not).
export function precreateRconIni(serverConfigPath, serverName, rconPassword, rconPort) {
  try {
    const iniPath = path.join(serverConfigPath, `${serverName}.ini`);
    if (fs.existsSync(iniPath)) return false;

    if (!fs.existsSync(serverConfigPath)) {
      fs.mkdirSync(serverConfigPath, { recursive: true });
    }
    const safeRconPw = sanitizeIniValue(rconPassword);
    const minimalIni = `# Auto-generated by Zomboid Control Panel\n# PZ will add remaining default settings on first server start\nRCONPort=${rconPort}\nRCONPassword=${safeRconPw}\n`;
    writeFileAtomic(iniPath, minimalIni, { encoding: "utf-8", mode: 0o600 });
    log.info(`Pre-created INI with RCON settings at ${iniPath}`);
    return true;
  } catch (iniError) {
    log.warn(`Failed to pre-create INI: ${iniError.message}`);
    return false;
  }
}

// Copies the bundled PanelBridge Lua mod into a freshly installed server, if
// the mod source is found alongside the panel binary/cwd. Returns whether it
// was installed so callers can track it (install.js emits an io log line,
// quick-setup.js reports it in the response body).
export function installPanelBridgeMod(installPath) {
  try {
    const possibleModPaths = [
      path.join(process.cwd(), "pz-mod", "PanelBridge"),
      path.join(path.dirname(process.execPath), "pz-mod", "PanelBridge"),
    ];

    let modSourcePath = null;
    for (const p of possibleModPaths) {
      if (fs.existsSync(p)) {
        modSourcePath = p;
        break;
      }
    }

    if (!modSourcePath) return false;

    const sourceLuaFile = path.join(
      modSourcePath,
      "media",
      "lua",
      "server",
      "PanelBridge.lua",
    );
    const destLuaDir = path.join(installPath, "media", "lua", "server");
    const destLuaFile = path.join(destLuaDir, "PanelBridge.lua");

    if (!fs.existsSync(sourceLuaFile)) return false;

    if (!fs.existsSync(destLuaDir)) {
      fs.mkdirSync(destLuaDir, { recursive: true });
    }
    fs.copyFileSync(sourceLuaFile, destLuaFile);
    log.info("PanelBridge mod auto-installed to server");
    return true;
  } catch (modError) {
    log.warn(`Failed to auto-install PanelBridge mod: ${modError.message}`);
    return false;
  }
}
