// Helpers used by lifecycle.js's POST /start route: writing RCON credentials
// into the server .ini before/while the process boots, and the background
// polling loop that waits for the process + RCON to come up after start.
import path from "path";
import fs from "fs";
import { createLogger } from "../../utils/logger.js";
import { getActiveServer } from "../../database/init.js";
import { sanitizeIniValue } from "../../utils/sanitize.js";
import { withFileLock, writeFileAtomic } from "../../utils/fileWriteQueue.js";

const log = createLogger("API:Server");

// Helper to auto-configure RCON in the server's .ini file
// Called BEFORE server starts to ensure PZ reads the correct RCON credentials on boot.
// If the INI file doesn't exist yet (first run), creates the directory + a minimal INI
// so PZ will merge its defaults with our RCON settings instead of generating a blank password.
export async function ensureRconConfigured() {
  try {
    const activeServer = await getActiveServer();
    if (!activeServer) {
      log.debug("ensureRconConfigured: No active server");
      return false;
    }

    const serverConfigPath =
      activeServer.serverConfigPath ||
      (activeServer.zomboidDataPath
        ? path.join(activeServer.zomboidDataPath, "Server")
        : null);
    const serverName = activeServer.serverName;
    const rconPassword = activeServer.rconPassword;
    const rconPort = activeServer.rconPort || 27015;

    if (!serverConfigPath || !serverName) {
      log.debug("ensureRconConfigured: Missing serverConfigPath or serverName");
      return false;
    }

    if (!rconPassword) {
      log.debug("ensureRconConfigured: No RCON password configured");
      return false;
    }

    const iniPath = path.join(serverConfigPath, `${serverName}.ini`);

    // Locked per-path: two overlapping calls (e.g. a start request racing a
    // settings save) must not interleave their read-modify-write of the INI.
    return await withFileLock(iniPath, async () => {
      // If the INI doesn't exist, pre-create it with RCON settings so PZ reads them on first boot
      if (!fs.existsSync(iniPath)) {
        log.info(
          `ensureRconConfigured: INI not found — pre-creating ${iniPath} with RCON settings`,
        );
        try {
          // Ensure the Server/ directory exists
          if (!fs.existsSync(serverConfigPath)) {
            fs.mkdirSync(serverConfigPath, { recursive: true });
            log.info(`Created server config directory: ${serverConfigPath}`);
          }
          const safePassword = sanitizeIniValue(rconPassword);
          // Create minimal INI — PZ will fill in all other defaults on first boot
          const minimalIni = `# Auto-generated by Zomboid Control Panel\n# PZ will add remaining default settings on first server start\nRCONPort=${rconPort}\nRCONPassword=${safePassword}\n`;
          writeFileAtomic(iniPath, minimalIni, {
            encoding: "utf-8",
            mode: 0o600,
          });
          log.info(`Pre-created INI with RCON settings (port: ${rconPort})`);
          return true;
        } catch (createError) {
          log.error(`Failed to pre-create INI file: ${createError.message}`);
          return false;
        }
      }

      // INI exists — check if RCON is already configured correctly
      let content = fs.readFileSync(iniPath, "utf-8").replace(/\r\n/g, "\n");
      const hasCorrectPassword = content.includes(
        `RCONPassword=${rconPassword}`,
      );
      const hasCorrectPort = content.includes(`RCONPort=${rconPort}`);

      if (hasCorrectPassword && hasCorrectPort) {
        log.debug("ensureRconConfigured: RCON already configured correctly");
        return true;
      }

      // Update RCON settings in the .ini file
      log.info(`Auto-configuring RCON in ${iniPath}`);

      // Update RCONPassword (sanitize to prevent INI injection via newlines)
      const safePassword = sanitizeIniValue(rconPassword);
      if (content.includes("RCONPassword=")) {
        content = content.replace(
          /RCONPassword=.*/g,
          () => `RCONPassword=${safePassword}`,
        );
      } else {
        content += `\nRCONPassword=${safePassword}`;
      }

      // Update RCONPort
      if (content.includes("RCONPort=")) {
        content = content.replace(/RCONPort=.*/g, () => `RCONPort=${rconPort}`);
      } else {
        content += `\nRCONPort=${rconPort}`;
      }

      writeFileAtomic(iniPath, content, { encoding: "utf-8", mode: 0o600 });
      log.info("RCON auto-configured successfully in server .ini file");
      return true;
    });
  } catch (error) {
    log.error(`ensureRconConfigured error: ${error.message}`);
    return false;
  }
}

// Polls for the server process to come up, then polls for RCON to accept a
// connection, and finally clears the "server starting" flag so the RCON
// service's own auto-reconnect can take over. Runs fire-and-forget — the
// /start route does not await this, matching the original inline behavior.
export function startServerReadyPolling({ serverManager, rconService, io, discordBot }) {
  let attempts = 0;
  const maxAttempts = 30; // 30 seconds max
  let pollCleared = false;

  const pollInterval = setInterval(async () => {
    if (pollCleared) return; // Safety check
    try {
      attempts++;
      const isRunning = await serverManager.checkServerRunning();

      if (isRunning) {
        pollCleared = true;
        clearInterval(pollInterval);
        if (io) io.emit("server:status", { running: true });
        log.info("Server detected as running");

        // Wait for RCON to be ready (PZ takes 60-180s to fully start)
        // Look for open port instead of blindly waiting
        // Keep serverStarting=true the whole time to block auto-reconnect
        log.info("Waiting for RCON to be ready - starting port polling...");

        await rconService.loadConfig(); // Ensure clean config
        const rconHost = rconService.config.host || "127.0.0.1";
        const rconPort = rconService.config.port || 27015;
        log.info(
          `Monitoring TCP port ${rconHost}:${rconPort} for activity...`,
        );

        let rconConnected = false;
        let rconConfigured = false;
        let portOpen = false;

        // Poll port for up to 5 minutes (300 seconds) - checking every 5 seconds
        const maxPollAttempts = 60;

        for (let i = 0; i < maxPollAttempts; i++) {
          // 1. Check if port is open (if not already found)
          if (!portOpen) {
            portOpen = await rconService.checkPortOpen(rconHost, rconPort);

            if (!portOpen) {
              log.debug(
                `RCON startup: Port ${rconHost}:${rconPort} not yet open (poll ${i + 1}/${maxPollAttempts})...`,
              );
              // Wait 5 seconds before next check
              await new Promise((r) => setTimeout(r, 5000));

              // Periodically try to configure RCON (Wait for .ini to appear)
              if (!rconConfigured && i % 3 === 0) {
                // Every 15s (3 * 5s)
                rconConfigured = await ensureRconConfigured();
                if (rconConfigured) {
                  log.info(
                    "RCON settings auto-configured in server .ini file during startup wait",
                  );
                }
              }
              continue;
            }
            log.info(
              `RCON port ${rconHost}:${rconPort} is now open! Initiating connection...`,
            );
          }

          // 2. Port is open, try to connect
          // Reset connection state before attempt to clear any stalled state
          if (rconService.forceResetConnectionState) {
            rconService.forceResetConnectionState();
          }

          try {
            // Attempt connection with a 15s timeout
            const connectPromise = rconService.connect();
            const timeoutPromise = new Promise((_, reject) =>
              setTimeout(
                () =>
                  reject(new Error("Connection attempt timed out after 15s")),
                15000,
              ),
            );

            await Promise.race([connectPromise, timeoutPromise]);

            if (rconService.connected) {
              log.info("RCON connected successfully after server startup");
              rconConnected = true;
              break;
            } else {
              log.warn(
                `RCON connected to port but authentication/handshake failed. Retrying...`,
              );
              // Wait a bit before retry if port is open but auth fails (service might be starting up)
              await new Promise((r) => setTimeout(r, 5000));
            }
          } catch (e) {
            log.warn(`RCON connection attempt failed: ${e.message}`);
            await new Promise((r) => setTimeout(r, 5000));
          }
        }

        // Log completion status
        if (rconConnected) {
          log.info("RCON startup sequence completed - connected");
          discordBot
            ?.sendEventNotification("serverStart", {})
            .catch((err) =>
              log.debug(
                `Discord serverStart notification failed: ${err.message}`,
              ),
            );
        } else {
          log.warn(
            "RCON startup sequence completed - NOT connected (auto-reconnect will keep trying every 30s)",
          );
        }

        // Clear the flag when done - now auto-reconnect can take over
        if (rconService.setServerStarting) {
          rconService.setServerStarting(false);
        } else {
          rconService.serverStarting = false;
        }
      } else if (attempts >= maxAttempts) {
        pollCleared = true;
        clearInterval(pollInterval);
        if (rconService.setServerStarting) {
          rconService.setServerStarting(false);
        } else {
          rconService.serverStarting = false;
        }
        log.warn("Server start polling timed out");
      }
    } catch (err) {
      // Clear interval on error to prevent memory leak
      pollCleared = true;
      clearInterval(pollInterval);
      if (rconService.setServerStarting) {
        rconService.setServerStarting(false);
      } else {
        rconService.serverStarting = false;
      }
      log.error(`Server status poll failed: ${err.message}`);
    }
  }, 1000);
}
